# params.yaml
data_ingestion:
  data_url: "akshaydattatraykhare/diabetes-dataset"
  file_name: "diabetes.csv"
  raw_data_path: "./data"

data_preprocessing:
  test_size: 0.20
  val_size: 0.25
  random_state: 42
  target_column: "Outcome"
  columns:
    - Glucose
    - BloodPressure
    - SkinThickness
    - Insulin
    - BMI
  
model_building:
  target_column: "Outcome"
  penalty: "l2"
  solver: "liblinear"
  C: 0.1
  class_weight: ~
  random_state: 42

model_evaluation:
  target_column: "Outcome"

mlflow:
  tracking_mode: "local"   # local | dagshub
  experiment_name: "my-dvc-diabetes-pipeline"
  model_name: diabetes_prediction_model

  repo_owner: "prashanthule6999"
  repo_name: "SL-Diabetes-MLOps"

  tracking_uri: "https://dagshub.com/prashanthule6999/SL-Diabetes-MLOps.mlflow"