name: CI/CD Pipeline

on: push

jobs:
  project-testing:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.15'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip uninstall -y pathspec || true
          pip install -r requirements.txt

      - name: run pipeline
        env:
          SL_DIABETES: ${{ secrets.SL_DIABETES }}
        run: |
          dvc repro